pending_urls:
- https://huggingface.co/learn/llm-course/chapter12/1
processed_urls:
- https://mp.weixin.qq.com/s/EQUn3ePBDd-xl9TnOvLLng
- https://mp.weixin.qq.com/s/4QxbgUzrfsa3eooshkB-kQ
- https://mp.weixin.qq.com/s/GUaoTn9F59Wtr5Fxl3Yb3A
- https://mp.weixin.qq.com/s/0vAWHzlEZnhZYolHTvM1bg
- https://mp.weixin.qq.com/s/hLR_QsHz14PkCUwoILO-hg
- https://mp.weixin.qq.com/s/Gr1cAELfr7X3mFW5ynRWsA
- https://mp.weixin.qq.com/s/BgrcbJnD_Q27xQT4cLBtfg
- https://mp.weixin.qq.com/s/bGfSslTMqAZwGiSdMw2bBw
- https://huggingface.co/learn/llm-course/
- https://huggingface.co/learn/llm-course
- https://huggingface.co/learn/llm-course/chapter0/1
- https://huggingface.co/learn/llm-course/chapter1/1
- https://huggingface.co/learn/llm-course/chapter2/1
- https://huggingface.co/learn/llm-course/chapter3/1
- https://huggingface.co/learn/llm-course/chapter4/1
- https://huggingface.co/learn/llm-course/chapter5/1
- https://huggingface.co/learn/llm-course/chapter6/1
- https://huggingface.co/learn/llm-course/chapter7/1
- https://huggingface.co/learn/llm-course/chapter8/1
- https://huggingface.co/learn/llm-course/chapter9/1
- https://huggingface.co/learn/llm-course/chapter10/1
- https://huggingface.co/learn/llm-course/chapter11/1
